import unittest

from lagebild import (
    Issue,
    Milestone,
    ProjectSnapshot,
    PullRequest,
    assert_read_only_gh_args,
    has_review_of_record_evidence,
    parse_project_register,
    render_portfolio,
)


PROJECT_MD = """
# Example Project

Phase: Beta

Zielbild: Operators can inspect project state without a dashboard.

## Teilprojekte & Produktversprechen

| Teilprojekt / Milestone | Produktversprechen | Status (`offen` / `bestätigt`) | Evidence-Link | phasenkritisch (`ja` / `nein`) |
|---|---|---|---|---|
| Core Loop | Closeout is evidence-first | bestätigt | https://example.test/pr/1 | ja |
| Core Loop | Morning review stays human-led | offen |  | ja |
"""


class LagebildTests(unittest.TestCase):
    def test_parse_project_register_extracts_phase_target_and_promises(self):
        register = parse_project_register(PROJECT_MD)

        self.assertEqual(register.phase, "Beta")
        self.assertEqual(
            register.target_picture,
            "Operators can inspect project state without a dashboard.",
        )
        self.assertEqual(len(register.promises), 2)
        self.assertEqual(register.promises[0].milestone, "Core Loop")
        self.assertEqual(register.promises[0].status, "bestätigt")
        self.assertTrue(register.promises[0].phase_critical)
        self.assertEqual(register.promises[1].evidence_url, "")

    def test_render_portfolio_has_required_sections_and_no_percent_sign(self):
        snapshot = ProjectSnapshot(
            repo="example-org/example-repo",
            repo_url="https://github.com/example-org/example-repo",
            phase="Beta",
            target_picture="Operators can inspect project state.",
            milestones=[
                Milestone(
                    title="Core Loop",
                    state="open",
                    url="https://github.com/example-org/example-repo/milestone/1",
                    open_issues=1,
                    closed_issues=1,
                )
            ],
            issues=[
                Issue(
                    number=1,
                    title="Blocked item",
                    state="OPEN",
                    url="https://github.com/example-org/example-repo/issues/1",
                    labels=["blocked"],
                    milestone="Core Loop",
                ),
                Issue(
                    number=2,
                    title="Closed without PR",
                    state="CLOSED",
                    url="https://github.com/example-org/example-repo/issues/2",
                    labels=[],
                    milestone="Core Loop",
                ),
                Issue(
                    number=3,
                    title="Missing milestone",
                    state="OPEN",
                    url="https://github.com/example-org/example-repo/issues/3",
                    labels=[],
                    milestone=None,
                ),
            ],
            pull_requests=[
                PullRequest(
                    number=10,
                    title="Delivery PR",
                    state="MERGED",
                    url="https://github.com/example-org/example-repo/pull/10",
                    body="Closes #99",
                    labels=["review:pass"],
                    merged_at="2026-07-03T00:00:00Z",
                )
            ],
            project_md_found=True,
            promises=parse_project_register(PROJECT_MD).promises,
        )

        output = render_portfolio([snapshot], generated_at="2026-07-03T00:00:00Z")

        self.assertIn("<!-- GENERATED by pm/lagebild.py", output)
        self.assertIn("## Portfolio-Übersicht", output)
        self.assertIn("## Projekt: example-org/example-repo", output)
        self.assertIn("### Teilprojekte", output)
        self.assertIn("### Issues ohne Milestone", output)
        self.assertIn("### Geschlossene Issues ohne merged PR-Beleg", output)
        self.assertIn("### Offene Human Gates", output)
        self.assertIn("### Unklare Versprechen ohne Evidence-Link", output)
        self.assertIn("[#3 Missing milestone]", output)
        self.assertIn("[#2 Closed without PR]", output)
        self.assertIn("[#1 Blocked item]", output)
        self.assertNotIn("%", output)

    def test_render_portfolio_uses_review_comment_evidence(self):
        snapshot = ProjectSnapshot(
            repo="example-org/example-repo",
            repo_url="https://github.com/example-org/example-repo",
            phase="Beta",
            target_picture="Operators can inspect project state.",
            milestones=[],
            issues=[
                Issue(
                    number=4,
                    title="Reviewed delivery",
                    state="CLOSED",
                    url="https://github.com/example-org/example-repo/issues/4",
                    labels=[],
                    milestone=None,
                )
            ],
            pull_requests=[
                PullRequest(
                    number=20,
                    title="Reviewed PR",
                    state="MERGED",
                    url="https://github.com/example-org/example-repo/pull/20",
                    body="Closes #4",
                    labels=[],
                    merged_at="2026-07-03T00:00:00Z",
                    review_evidence_texts=["Review of Record: PASS\nLooks merge-ready."],
                )
            ],
            project_md_found=True,
            promises=[],
        )

        output = render_portfolio([snapshot], generated_at="2026-07-03T00:00:00Z")

        self.assertIn("PR #20 Reviewed PR", output)
        self.assertIn("Review of Record sichtbar", output)

    def test_render_portfolio_keeps_review_unknown_without_evidence(self):
        snapshot = ProjectSnapshot(
            repo="example-org/example-repo",
            repo_url="https://github.com/example-org/example-repo",
            phase="Beta",
            target_picture="Operators can inspect project state.",
            milestones=[],
            issues=[
                Issue(
                    number=5,
                    title="Unreviewed delivery",
                    state="CLOSED",
                    url="https://github.com/example-org/example-repo/issues/5",
                    labels=[],
                    milestone=None,
                )
            ],
            pull_requests=[
                PullRequest(
                    number=21,
                    title="Unreviewed PR",
                    state="MERGED",
                    url="https://github.com/example-org/example-repo/pull/21",
                    body="Closes #5",
                    labels=[],
                    merged_at="2026-07-03T00:00:00Z",
                )
            ],
            project_md_found=True,
            promises=[],
        )

        output = render_portfolio([snapshot], generated_at="2026-07-03T00:00:00Z")

        self.assertIn("PR #21 Unreviewed PR", output)
        self.assertIn("Review unklar", output)

    def test_review_evidence_patterns_cover_body_and_review_pass_comment(self):
        body_evidence = PullRequest(
            number=22,
            title="Body evidence",
            state="MERGED",
            url="https://github.com/example-org/example-repo/pull/22",
            body="Review of Record: PASS\nCloses #6",
            labels=[],
            merged_at="2026-07-03T00:00:00Z",
        )
        comment_evidence = PullRequest(
            number=23,
            title="Comment evidence",
            state="MERGED",
            url="https://github.com/example-org/example-repo/pull/23",
            body="Closes #7",
            labels=[],
            merged_at="2026-07-03T00:00:00Z",
            review_evidence_texts=["Review-PASS"],
        )

        self.assertTrue(has_review_of_record_evidence(body_evidence))
        self.assertTrue(has_review_of_record_evidence(comment_evidence))

    def test_read_only_gh_guard_rejects_mutating_commands(self):
        mutating_commands = [
            ["gh", "issue", "edit", "1"],
            ["gh", "pr", "merge", "1"],
            ["gh", "api", "-X", "PATCH", "repos/example"],
            ["gh", "api", "--method", "DELETE", "repos/example"],
        ]

        for args in mutating_commands:
            with self.subTest(args=args):
                with self.assertRaises(ValueError):
                    assert_read_only_gh_args(args)

        assert_read_only_gh_args(["gh", "issue", "list", "--repo", "example-org/example-repo"])


if __name__ == "__main__":
    unittest.main()
